import CucumberSwiftGherkin
@testable import CucumberSwiftTestingGenerator
import XCTest

final class SwiftTestingSourceTests: XCTestCase {
    func generate(_ text: String, path: String = "/Features/Test.feature") -> String {
        SwiftTestingSource.generate([.init(path: path, file: FeatureFile(parsing: text, uri: path))])
    }

    func testAScenarioIsATestInItsFeaturesSuite() {
        let source = generate("""
        @fruit
        Feature: Eat fruit
          Scenario: Eat an apple
            Given an apple
        """)
        XCTAssertEqual(source, #"""
        // Generated by CucumberSwiftTestingPlugin from this target's feature files. Do not edit.

        import CucumberSwiftTesting
        import Testing

        /// Every feature in the target. Serialized, because CucumberSwift runs one scenario at a time, and
        /// step definitions often share state.
        @MainActor
        @Suite("Features", .serialized)
        struct CucumberFeatures {
            @MainActor
            @Suite("Eat fruit")
            struct EatFruit {
                @Test("Eat an apple", .enabled(if: CucumberSwiftTesting.CucumberTags.shouldRun(["fruit"])))
                func EatAnApple() async {
                    await CucumberSwiftTesting.Cucumber.shared.run(
                        CucumberSwiftTesting.GherkinScenario(
                            featureTitle: "Eat fruit",
                            featureTags: ["fruit"],
                            title: "Eat an apple",
                            tags: ["fruit"],
                            file: "/Features/Test.feature",
                            line: 3,
                            column: 3,
                            steps: [
                                CucumberSwiftTesting.GherkinStep(
                                    keyword: [.given],
                                    keywordName: "Given",
                                    text: "an apple",
                                    line: 4,
                                    column: 5,
                                    suggestion: "Given(\"an apple\") { _, _ in\n    Issue.record(\"Step not implemented: replace this line with your test code\")\n}")
                            ]))
                }

            }

        }

        """#)
    }

    func testAScenarioOutlineIsAParameterizedTestWithACaseForEachExample() {
        let source = generate("""
        Feature: Cukes
          Scenario Outline: Eat <eaten>
            Given I have <start> cukes
              | left   |
              | <left> |

            Examples:
              | start | eaten | left |
              | 12    | 5     | 7    |
              | 20    | 5     | 15   |
        """)
        XCTAssertTrue(source.contains(#"@Test("Eat <eaten>", arguments: ["#), source)
        XCTAssertTrue(source.contains(#"].filter { CucumberSwiftTesting.CucumberTags.shouldRun($0.scenario.tags) })"#), source)
        XCTAssertTrue(source.contains("func EatEaten(_ example: CucumberSwiftTesting.GherkinExample) async {"), source)
        XCTAssertTrue(source.contains("await CucumberSwiftTesting.Cucumber.shared.run(example.scenario)"), source)
        XCTAssertEqual(source.components(separatedBy: "CucumberSwiftTesting.GherkinExample(\n").count - 1, 2)
        XCTAssertTrue(source.contains(#"title: "Eat 5 (start: 12, left: 7)","#), source)
        XCTAssertTrue(source.contains(#"title: "Eat 5 (start: 20, left: 15)","#), source)
        XCTAssertTrue(source.contains(#"text: "I have 12 cukes","#), source)
        XCTAssertTrue(source.contains(#"dataTable: [["left"], ["15"]],"#), source)
        XCTAssertTrue(source.contains("line: 9,"), source)
        XCTAssertTrue(source.contains("line: 10,"), source)
    }

    func testStepsHaveTheirDocStringsAndContinuedKeywords() {
        let source = generate(#"""
        Feature: F
          Scenario: S
            Given a document
              """json
              {"a": "\(b)"}
              """
            And another step
        """#)
        XCTAssertTrue(source.contains(#"docString: CucumberSwiftTesting.DocString(literal: "{\"a\": \"\\(b)\"}", rawLiteral: "#), source)
        XCTAssertTrue(source.contains(#"contentType: "json")"#), source)
        XCTAssertTrue(source.contains("keyword: [.given, .and],"), source)
        XCTAssertTrue(source.contains(#"keywordName: "Given","#), source)
    }

    func testALocalizedFeatureFileIsReadInItsLanguage() {
        let source = generate("""
        # language: es
        Característica: Comer
          Escenario: Uno
            Dado un paso
        """)
        XCTAssertTrue(source.contains("struct Comer {"), source)
        XCTAssertTrue(source.contains("func Uno() async {"), source)
        XCTAssertTrue(source.contains("keyword: [.given],"), source)
        XCTAssertTrue(source.contains(#"text: "un paso","#), source)
    }

    func testProblemsInAFeatureFileFailATest() {
        let source = generate("# language: xx\nFeature: F\n  Scenario: S\n    Given a step\n", path: "/Features/Bad.feature")
        XCTAssertTrue(source.contains(#"@Test("Feature files are valid Gherkin")"#), source)
        let location = #"SourceLocation(fileID: "Features/Bad.feature", filePath: "/Features/Bad.feature", line: 1, column: 1)"#
        XCTAssertTrue(source.contains(#"Issue.record("File: Bad.feature declares an unsupported language", sourceLocation: "# + location + ")"), source)
    }

    func testAFeatureWithoutScenariosHasNoSuite() {
        XCTAssertFalse(generate("Feature: Empty\n").contains("struct Empty"))
    }

    func testNamesAreUniqueAndNeverHideWhatTheGeneratedCodeUses() {
        var used = Set<String>()
        XCTAssertEqual(SwiftTestingSource.uniqueName("EatCukes", fallback: "Scenario", in: &used), "EatCukes")
        XCTAssertEqual(SwiftTestingSource.uniqueName("EatCukes", fallback: "Scenario", in: &used), "EatCukes_2")
        XCTAssertEqual(SwiftTestingSource.uniqueName("", fallback: "Scenario", in: &used), "Scenario")
        XCTAssertEqual(SwiftTestingSource.uniqueName("Test", fallback: "Scenario", in: &used), "Scenario_2")
        XCTAssertEqual(SwiftTestingSource.uniqueName("CucumberSwiftTesting", fallback: "Feature", in: &used), "Feature")
    }

    func testTwoScenariosWithTheSameTitleGetTwoTests() {
        let source = generate("""
        Feature: F
          Scenario: Same
            Given a step
          Scenario: Same
            Given a step
          Scenario: 🥒
            Given a step
        """)
        XCTAssertTrue(source.contains("func Same() async {"), source)
        XCTAssertTrue(source.contains("func Same_2() async {"), source)
        XCTAssertTrue(source.contains(#"@Test("🥒", .enabled"#), source)
        XCTAssertTrue(source.contains("func Scenario() async {"), source)
    }

    func testTextIsAlwaysAValidStringLiteral() {
        XCTAssertEqual(SwiftTestingSource.literal(#"a "quoted" \(interpolation)"#), #""a \"quoted\" \\(interpolation)""#)
        XCTAssertEqual(SwiftTestingSource.literal("two\nlines\tand\r\u{0}"), #""two\nlines\tand\r\u{0}""#)
        XCTAssertEqual(SwiftTestingSource.literal("Pepinos en español 🥒"), "\"Pepinos en español 🥒\"")
    }
}
