//
//  SwiftTestingSource.swift
//  CucumberSwiftTestingGenerator
//

import CucumberSwiftGherkin
import Foundation

/// The Swift Testing source for a target's feature files: one suite for all of them, serialized as
/// CucumberSwift runs one scenario at a time; in it a suite per feature; in that a test per Scenario,
/// and a parameterized test per Scenario Outline, with a test case per example.
enum SwiftTestingSource {
    /// A parsed feature file and its path.
    struct Input {
        let path: String
        let file: FeatureFile
    }

    /// What a generated `GherkinScenario` holds besides its feature: a Scenario's, or an example's.
    private struct ScenarioParts {
        let title: String
        let tags: [String]
        let line: Int
        let column: Int
        let steps: [FeatureFile.Step]
    }

    /// The last line of a suggested step definition, which fails the step until it is filled in.
    static let failure = "Issue.record(\"Step not implemented: replace this line with your test code\")"

    /// Names the generated code can't use for a suite or a test: they would hide what it refers to.
    static let reservedNames: Set<String> = [
        "CucumberFeatures", "CucumberSwiftTesting", "Testing", "Test", "Suite", "Self", "Type", "Protocol", "Any", "Sendable"
    ]

    static func generate(_ inputs: [Input]) -> String {
        var source = """
        // Generated by CucumberSwiftTestingPlugin from this target's feature files. Do not edit.
        //
        // One suite holds every feature in the target. It is serialized, because CucumberSwift runs one
        // scenario at a time, and step definitions often share state, and a failed expectation is reported
        // in the feature file. This comment is here rather than on the suite, where Swift Testing would show
        // it with each failure.

        import CucumberSwiftTesting
        import Testing

        @MainActor
        @Suite("Features", .serialized, .reportedInFeatureFiles)
        struct CucumberFeatures {

        """
        let problems = inputs.flatMap { input in input.file.problems.map { (path: input.path, problem: $0) } }
        if !problems.isEmpty {
            source += gherkinTest(problems)
        }
        var suiteNames = Set<String>()
        for input in inputs {
            for feature in input.file.features where !feature.scenarios.isEmpty {
                let name = uniqueName(FeatureFile.typeName(for: feature.title), fallback: "Feature", in: &suiteNames)
                source += suite(for: feature, named: name, path: input.path)
            }
        }
        return source + "}\n"
    }

    /// A test that fails with each problem in the feature files, as CucumberSwift's `testGherkin()` does.
    private static func gherkinTest(_ problems: [(path: String, problem: String)]) -> String {
        let issues = problems.map { problem in
            let fileID = literal("Features/" + URL(fileURLWithPath: problem.path).lastPathComponent)
            let location = "SourceLocation(fileID: \(fileID), filePath: \(literal(problem.path)), line: 1, column: 1)"
            return "        Issue.record(\(literal(problem.problem)), sourceLocation: \(location))"
        }
        return """
            @Test("Feature files are valid Gherkin")
            func gherkin() {
        \(issues.joined(separator: "\n"))
            }


        """
    }

    private static func suite(for feature: FeatureFile.Feature, named name: String, path: String) -> String {
        var source = """
            @MainActor
            @Suite\(displayName(feature.title))
            struct \(name) {

        """
        var testNames = Set<String>()
        for scenario in feature.scenarios {
            let testName = uniqueName(FeatureFile.typeName(for: scenario.title), fallback: "Scenario", in: &testNames)
            source += test(for: scenario, named: testName, in: feature, path: path)
        }
        return source + "    }\n\n"
    }

    private static func test(
        for scenario: FeatureFile.Scenario,
        named name: String,
        in feature: FeatureFile.Feature,
        path: String
    ) -> String {
        let displayName = scenario.title.isEmpty ? "" : literal(scenario.title) + ", "
        guard let examples = scenario.examples else {
            let parts = ScenarioParts(
                title: scenario.title,
                tags: scenario.tags,
                line: scenario.line,
                column: scenario.column,
                steps: scenario.steps)
            return """
                    @Test(\(displayName).enabled(if: CucumberSwiftTesting.CucumberTags.shouldRun(\(array(scenario.tags)))))
                    func \(name)() async {
                        await CucumberSwiftTesting.Cucumber.shared.run(
            \(gherkinScenario(parts, of: feature, path: path, indent: 16)))
                    }


            """
        }
        let arguments = examples.map { example in
            let parts = ScenarioParts(title: example.title, tags: example.tags, line: example.line, column: example.column, steps: example.steps)
            return "            CucumberSwiftTesting.GherkinExample(\n" + gherkinScenario(parts, of: feature, path: path, indent: 16) + ")"
        }
        return """
                @Test(\(displayName)arguments: [
        \(arguments.joined(separator: ",\n"))
                ].filter { CucumberSwiftTesting.CucumberTags.shouldRun($0.scenario.tags) })
                func \(name)(_ example: CucumberSwiftTesting.GherkinExample) async {
                    await CucumberSwiftTesting.Cucumber.shared.run(example.scenario)
                }


        """
    }

    private static func gherkinScenario(_ parts: ScenarioParts, of feature: FeatureFile.Feature, path: String, indent: Int) -> String {
        let pad = String(repeating: " ", count: indent)
        let stepLines = parts.steps.map { pad + "        " + gherkinStep($0, indent: indent + 8) }
        return pad + "CucumberSwiftTesting.GherkinScenario(\n"
            + pad + "    featureTitle: \(literal(feature.title)),\n"
            + pad + "    featureTags: \(array(feature.tags)),\n"
            + pad + "    title: \(literal(parts.title)),\n"
            + pad + "    tags: \(array(parts.tags)),\n"
            + pad + "    file: \(literal(path)),\n"
            + pad + "    line: \(parts.line),\n"
            + pad + "    column: \(parts.column),\n"
            + pad + "    steps: [\n"
            + stepLines.joined(separator: ",\n") + (stepLines.isEmpty ? "" : "\n")
            + pad + "    ])"
    }

    private static func gherkinStep(_ step: FeatureFile.Step, indent: Int) -> String {
        let pad = String(repeating: " ", count: indent)
        let keywords = FeatureFile.Keyword.allCases.filter(step.keywords.contains).map { ".\($0.rawValue)" }
        var arguments = [
            "keyword: [\(keywords.joined(separator: ", "))]",
            "keywordName: \(literal(step.keywordName))",
            "text: \(literal(step.text))",
            "line: \(step.line)",
            "column: \(step.column)"
        ]
        if let docString = step.docString {
            let contentType = docString.contentType.map(literal) ?? "nil"
            arguments.append("docString: CucumberSwiftTesting.DocString(literal: \(literal(docString.literal)), "
                             + "rawLiteral: \(literal(docString.rawLiteral)), contentType: \(contentType))")
        }
        if let dataTable = step.dataTable {
            arguments.append("dataTable: [\(dataTable.map(array).joined(separator: ", "))]")
        }
        arguments.append("suggestion: \(literal(step.suggestedStepDefinition(failure: failure)))")
        return "CucumberSwiftTesting.GherkinStep(\n"
            + arguments.map { pad + "    " + $0 }.joined(separator: ",\n")
            + ")"
    }

    /// `(“title”)` for a suite with a title, nothing for one without.
    private static func displayName(_ title: String) -> String {
        title.isEmpty ? "" : "(\(literal(title)))"
    }

    /// `name`, or `fallback` when it is empty or reserved, with a number added if it is already used.
    static func uniqueName(_ name: String, fallback: String, in used: inout Set<String>) -> String {
        let base = name.isEmpty || reservedNames.contains(name) ? fallback : name
        var candidate = base
        var count = 2
        while used.contains(candidate) {
            candidate = "\(base)_\(count)"
            count += 1
        }
        used.insert(candidate)
        return candidate
    }

    /// `text` as a Swift string literal.
    static func literal(_ text: String) -> String {
        var escaped = ""
        for scalar in text.unicodeScalars {
            switch scalar {
                case "\\": escaped += "\\\\"
                case "\"": escaped += "\\\""
                case "\n": escaped += "\\n"
                case "\r": escaped += "\\r"
                case "\t": escaped += "\\t"
                case _ where scalar.value < 0x20 || scalar.value == 0x7F:
                    escaped += "\\u{\(String(scalar.value, radix: 16))}"
                default: escaped.unicodeScalars.append(scalar)
            }
        }
        return "\"\(escaped)\""
    }

    private static func array(_ items: [String]) -> String {
        "[" + items.map(literal).joined(separator: ", ") + "]"
    }
}
