//
//  LocalizedStepDefinitionNames.swift
//  CucumberSwiftLintTool
//
//  Generated from CucumberSwift's Generated/I18n.swift by LocalizedStepDefinitionNameTests.
//  Do not edit: change I18n.swift, then rewrite this file as that test describes.
//

extension StepDefinition {
    /// The localized step definitions, such as `ES_Dado(…)`, and their macros, such as `#ES_Dado(…)`.
    static let localizedNames: [String] = [
        // Afrikaans
        "AF_Gegewe",
        "AF_Wanneer",
        "AF_Dan",
        "AF_En",
        "AF_Maar",
        // Armenian
        "AM_Դիցուք",
        "AM_Եթե",
        "AM_Երբ",
        "AM_Ապա",
        "AM_Եվ",
        "AM_Բայց",
        // Aragonese
        "AN_Dau",
        "AN_Dada",
        "AN_Daus",
        "AN_Dadas",
        "AN_Cuan",
        "AN_Alavez",
        "AN_Allora",
        "AN_Antonces",
        "AN_Y",
        "AN_E",
        "AN_Pero",
        // Arabic
        "AR_بفرض",
        "AR_متى",
        "AR_عندما",
        "AR_اذاً",
        "AR_ثم",
        "AR_و",
        "AR_لكن",
        // Asturian
        "AST_Dáu",
        "AST_Dada",
        "AST_Daos",
        "AST_Daes",
        "AST_Cuando",
        "AST_Entós",
        "AST_Y",
        "AST_Ya",
        "AST_Peru",
        // Azerbaijani
        "AZ_TutaqKi",
        "AZ_Verilir",
        "AZ_Əgər",
        "AZ_NəVaxtKi",
        "AZ_OHalda",
        "AZ_Və",
        "AZ_Həm",
        "AZ_Amma",
        "AZ_Ancaq",
        // Bulgarian
        "BG_Дадено",
        "BG_Когато",
        "BG_То",
        "BG_И",
        "BG_Но",
        // Malay
        "BM_Diberi",
        "BM_Bagi",
        "BM_Apabila",
        "BM_Maka",
        "BM_Kemudian",
        "BM_Dan",
        "BM_Tetapi",
        "BM_Tapi",
        // Bosnian
        "BS_Dato",
        "BS_Kada",
        "BS_Zatim",
        "BS_I",
        "BS_A",
        "BS_Ali",
        // Catalan
        "CA_Donat",
        "CA_Donada",
        "CA_Atès",
        "CA_Atesa",
        "CA_Quan",
        "CA_Aleshores",
        "CA_Cal",
        "CA_I",
        "CA_Però",
        // Czech
        "CS_Pokud",
        "CS_ZaPředpokladu",
        "CS_Když",
        "CS_Pak",
        "CS_ATaké",
        "CS_A",
        "CS_Ale",
        // Welsh
        "CY_GB_AnrhegedigA",
        "CY_GB_Pryd",
        "CY_GB_Yna",
        "CY_GB_A",
        "CY_GB_Ond",
        // Danish
        "DA_Givet",
        "DA_Når",
        "DA_Så",
        "DA_Og",
        "DA_Men",
        // German
        "DE_Angenommen",
        "DE_GegebenSei",
        "DE_GegebenSeien",
        "DE_Wenn",
        "DE_Dann",
        "DE_Und",
        "DE_Aber",
        // Greek
        "EL_Δεδομένου",
        "EL_Όταν",
        "EL_Τότε",
        "EL_Και",
        "EL_Αλλά",
        // Emoji
        "EM_😐",
        "EM_🎬",
        "EM_🙏",
        "EM_😂",
        "EM_😔",
        // Scouse
        "EN_SCOUSE_Givun",
        "EN_SCOUSE_YouseKnowWhenYouseGot",
        "EN_SCOUSE_Wun",
        "EN_SCOUSE_YouseKnowLikeWhen",
        "EN_SCOUSE_Dun",
        "EN_SCOUSE_DenYouseGotta",
        "EN_SCOUSE_An",
        "EN_SCOUSE_Buh",
        // Australian
        "EN_AU_YKnow",
        "EN_AU_ItSJustUnbelievable",
        "EN_AU_ButAtTheEndOfTheDayIReckon",
        "EN_AU_TooRight",
        "EN_AU_YeahNah",
        // LOLCAT
        "EN_LOL_ICanHaz",
        "EN_LOL_Wen",
        "EN_LOL_Den",
        "EN_LOL_An",
        "EN_LOL_But",
        // Old English
        "EN_OLD_Thurh",
        "EN_OLD_Þurh",
        "EN_OLD_Ðurh",
        "EN_OLD_Tha",
        "EN_OLD_Þa",
        "EN_OLD_Ða",
        "EN_OLD_ThaThe",
        "EN_OLD_ÞaÞe",
        "EN_OLD_ÐaÐe",
        "EN_OLD_Ond",
        "EN_OLD__7",
        "EN_OLD_Ac",
        // Pirate
        "EN_PIRATE_Gangway",
        "EN_PIRATE_Blimey",
        "EN_PIRATE_LetGoAndHaul",
        "EN_PIRATE_Aye",
        "EN_PIRATE_Avast",
        // Esperanto
        "EO_Donitaĵo",
        "EO_Komence",
        "EO_Se",
        "EO_Do",
        "EO_Kaj",
        "EO_Sed",
        // Spanish
        "ES_Dado",
        "ES_Dada",
        "ES_Dados",
        "ES_Dadas",
        "ES_Cuando",
        "ES_Entonces",
        "ES_Y",
        "ES_E",
        "ES_Pero",
        // Estonian
        "ET_Eeldades",
        "ET_Kui",
        "ET_Siis",
        "ET_Ja",
        "ET_Kuid",
        // Persian
        "FA_بافرض",
        "FA_هنگامی",
        "FA_آنگاه",
        "FA_و",
        "FA_اما",
        // Finnish
        "FI_Oletetaan",
        "FI_Kun",
        "FI_Niin",
        "FI_Ja",
        "FI_Mutta",
        // French
        "FR_Soit",
        "FR_EtantDonnéQue",
        "FR_EtantDonnéQu",
        "FR_EtantDonné",
        "FR_EtantDonnée",
        "FR_EtantDonnés",
        "FR_EtantDonnées",
        "FR_ÉtantDonnéQue",
        "FR_ÉtantDonnéQu",
        "FR_ÉtantDonné",
        "FR_ÉtantDonnée",
        "FR_ÉtantDonnés",
        "FR_ÉtantDonnées",
        "FR_Quand",
        "FR_Lorsque",
        "FR_Lorsqu",
        "FR_Alors",
        "FR_EtQue",
        "FR_EtQu",
        "FR_Et",
        "FR_MaisQue",
        "FR_MaisQu",
        "FR_Mais",
        // Irish
        "GA_CuirIGcásGo",
        "GA_CuirIGcásNach",
        "GA_CuirIGcásGur",
        "GA_CuirIGcásNár",
        "GA_NuairA",
        "GA_NuairNach",
        "GA_NuairBa",
        "GA_NuairNár",
        "GA_Ansin",
        "GA_Agus",
        "GA_Ach",
        // Gujarati
        "GJ_આપેલછે",
        "GJ_ક્યારે",
        "GJ_પછી",
        "GJ_અને",
        "GJ_પણ",
        // Galician
        "GL_Dado",
        "GL_Dada",
        "GL_Dados",
        "GL_Dadas",
        "GL_Cando",
        "GL_Entón",
        "GL_Logo",
        "GL_E",
        "GL_Mais",
        "GL_Pero",
        // Hebrew
        "HE_בהינתן",
        "HE_כאשר",
        "HE_אז",
        "HE_אזי",
        "HE_וגם",
        "HE_אבל",
        // Hindi
        "HI_अगर",
        "HI_यदि",
        "HI_चूंकि",
        "HI_जब",
        "HI_कदा",
        "HI_तब",
        "HI_तदा",
        "HI_और",
        "HI_तथा",
        "HI_पर",
        "HI_परन्तु",
        "HI_किन्तु",
        // Croatian
        "HR_Zadan",
        "HR_Zadani",
        "HR_Zadano",
        "HR_Kada",
        "HR_Kad",
        "HR_Onda",
        "HR_I",
        "HR_Ali",
        // Creole
        "HT_Sipoze",
        "HT_SipozeKe",
        "HT_Lè",
        "HT_Le",
        "HT_LèSaA",
        "HT_LeSaA",
        "HT_Ak",
        "HT_Epi",
        "HT_E",
        "HT_Men",
        // Hungarian
        "HU_Amennyiben",
        "HU_Adott",
        "HU_Majd",
        "HU_Ha",
        "HU_Amikor",
        "HU_Akkor",
        "HU_És",
        "HU_De",
        // Indonesian
        "ID_Dengan",
        "ID_Ketika",
        "ID_Maka",
        "ID_Dan",
        "ID_Tapi",
        // Icelandic
        "IS_Ef",
        "IS_Þegar",
        "IS_Þá",
        "IS_Og",
        "IS_En",
        // Italian
        "IT_Dato",
        "IT_Data",
        "IT_Dati",
        "IT_Date",
        "IT_Quando",
        "IT_Allora",
        "IT_E",
        "IT_Ma",
        // Japanese
        "JA_前提",
        "JA_もし",
        "JA_ならば",
        "JA_かつ",
        "JA_しかし",
        "JA_但し",
        "JA_ただし",
        // Javanese
        "JV_Nalika",
        "JV_Nalikaning",
        "JV_Manawa",
        "JV_Menawa",
        "JV_Njuk",
        "JV_Banjur",
        "JV_Lan",
        "JV_Tapi",
        "JV_Nanging",
        "JV_Ananging",
        // Georgian
        "KA_Მოცემული",
        "KA_Როდესაც",
        "KA_Მაშინ",
        "KA_Და",
        "KA_Მაგ­რამ",
        // Kannada
        "KN_ನೀಡಿದ",
        "KN_ಸ್ಥಿತಿಯನ್ನು",
        "KN_ನಂತರ",
        "KN_ಮತ್ತು",
        "KN_ಆದರೆ",
        // Korean
        "KO_조건",
        "KO_먼저",
        "KO_만일",
        "KO_만약",
        "KO_그러면",
        "KO_그리고",
        "KO_하지만",
        "KO_단",
        // Lithuanian
        "LT_Duota",
        "LT_Kai",
        "LT_Tada",
        "LT_Ir",
        "LT_Bet",
        // Luxemburgish
        "LU_Ugeholl",
        "LU_Wann",
        "LU_Dann",
        "LU_An",
        "LU_A",
        "LU_Awer",
        "LU_Mä",
        // Latvian
        "LV_Kad",
        "LV_Ja",
        "LV_Tad",
        "LV_Un",
        "LV_Bet",
        // Macedonian
        "MK_CYRL_Дадено",
        "MK_CYRL_Дадена",
        "MK_CYRL_Кога",
        "MK_CYRL_Тогаш",
        "MK_CYRL_И",
        "MK_CYRL_Но",
        // Macedonian (Latin)
        "MK_LATN_Dadeno",
        "MK_LATN_Dadena",
        "MK_LATN_Koga",
        "MK_LATN_Togash",
        "MK_LATN_I",
        "MK_LATN_No",
        // Mongolian
        "MN_ӨгөгдсөнНь",
        "MN_Анх",
        "MN_Хэрэв",
        "MN_Тэгэхэд",
        "MN_ҮүнийДараа",
        "MN_Мөн",
        "MN_Тэгээд",
        "MN_Гэхдээ",
        "MN_Харин",
        // Dutch
        "NL_Gegeven",
        "NL_Stel",
        "NL_Als",
        "NL_Wanneer",
        "NL_Dan",
        "NL_En",
        "NL_Maar",
        // Norwegian
        "NO_Gitt",
        "NO_Når",
        "NO_Så",
        "NO_Og",
        "NO_Men",
        // Panjabi
        "PA_ਜੇਕਰ",
        "PA_ਜਿਵੇਂਕਿ",
        "PA_ਜਦੋਂ",
        "PA_ਤਦ",
        "PA_ਅਤੇ",
        "PA_ਪਰ",
        // Polish
        "PL_Zakładając",
        "PL_Mając",
        "PL_ZakładającŻe",
        "PL_Jeżeli",
        "PL_Jeśli",
        "PL_Gdy",
        "PL_Kiedy",
        "PL_Wtedy",
        "PL_Oraz",
        "PL_I",
        "PL_Ale",
        // Portuguese
        "PT_Dado",
        "PT_Dada",
        "PT_Dados",
        "PT_Dadas",
        "PT_Quando",
        "PT_Então",
        "PT_Entao",
        "PT_E",
        "PT_Mas",
        // Romanian
        "RO_DateFiind",
        "RO_DatFiind",
        "RO_DatăFiind",
        "RO_DatiFiind",
        "RO_DațiFiind",
        "RO_DaţiFiind",
        "RO_Cand",
        "RO_Când",
        "RO_Atunci",
        "RO_Si",
        "RO_Și",
        "RO_Şi",
        "RO_Dar",
        // Russian
        "RU_Допустим",
        "RU_Дано",
        "RU_Пусть",
        "RU_Когда",
        "RU_Если",
        "RU_То",
        "RU_Затем",
        "RU_Тогда",
        "RU_И",
        "RU_КТомуЖе",
        "RU_Также",
        "RU_Но",
        "RU_А",
        "RU_Иначе",
        // Slovak
        "SK_Pokiaľ",
        "SK_ZaPredpokladu",
        "SK_Keď",
        "SK_Ak",
        "SK_Tak",
        "SK_Potom",
        "SK_A",
        "SK_ATiež",
        "SK_ATaktiež",
        "SK_AZároveň",
        "SK_Ale",
        // Slovenian
        "SL_Dano",
        "SL_Podano",
        "SL_Zaradi",
        "SL_Privzeto",
        "SL_Ko",
        "SL_Ce",
        "SL_Če",
        "SL_Kadar",
        "SL_Nato",
        "SL_Potem",
        "SL_Takrat",
        "SL_In",
        "SL_Ter",
        "SL_Toda",
        "SL_Ampak",
        "SL_Vendar",
        // Serbian
        "SR_CYRL_ЗаДато",
        "SR_CYRL_ЗаДате",
        "SR_CYRL_ЗаДати",
        "SR_CYRL_Када",
        "SR_CYRL_Кад",
        "SR_CYRL_Онда",
        "SR_CYRL_И",
        "SR_CYRL_Али",
        // Serbian (Latin)
        "SR_LATN_ZaDato",
        "SR_LATN_ZaDate",
        "SR_LATN_ZaDati",
        "SR_LATN_Kada",
        "SR_LATN_Kad",
        "SR_LATN_Onda",
        "SR_LATN_I",
        "SR_LATN_Ali",
        // Swedish
        "SV_Givet",
        "SV_När",
        "SV_Så",
        "SV_Och",
        "SV_Men",
        // Tamil
        "TA_கொடுக்கப்பட்ட",
        "TA_எப்போது",
        "TA_அப்பொழுது",
        "TA_மேலும்",
        "TA_மற்றும்",
        "TA_ஆனால்",
        // Thai
        "TH_กำหนดให้",
        "TH_เมื่อ",
        "TH_ดังนั้น",
        "TH_และ",
        "TH_แต่",
        // Telugu
        "TL_చెప్పబడినది",
        "TL_ఈపరిస్థితిలో",
        "TL_అప్పుడు",
        "TL_మరియు",
        "TL_కాని",
        // Klingon
        "TLH_GhuNoblu",
        "TLH_DaHGhuBejlu",
        "TLH_QaSDI",
        "TLH_Vaj",
        "TLH__Ej",
        "TLH_Latlh",
        "TLH__Ach",
        "TLH__A",
        // Turkish
        "TR_DiyelimKi",
        "TR_EğerKi",
        "TR_OZaman",
        "TR_Ve",
        "TR_Fakat",
        "TR_Ama",
        // Tatar
        "TT_Әйтик",
        "TT_Әгәр",
        "TT_Нәтиҗәдә",
        "TT_Һәм",
        "TT_Вә",
        "TT_Ләкин",
        "TT_Әмма",
        // Ukrainian
        "UK_Припустимо",
        "UK_ПрипустимоЩо",
        "UK_Нехай",
        "UK_Дано",
        "UK_Якщо",
        "UK_Коли",
        "UK_То",
        "UK_Тоді",
        "UK_І",
        "UK_АТакож",
        "UK_Та",
        "UK_Але",
        // Urdu
        "UR_اگر",
        "UR_بالفرض",
        "UR_فرضکیا",
        "UR_جب",
        "UR_پھر",
        "UR_تب",
        "UR_اور",
        "UR_لیکن",
        // Uzbek
        "UZ_Агар",
        "UZ_Унда",
        "UZ_Ва",
        "UZ_Лекин",
        "UZ_Бирок",
        "UZ_Аммо",
        // Vietnamese
        "VI_Biết",
        "VI_Cho",
        "VI_Khi",
        "VI_Thì",
        "VI_Và",
        "VI_Nhưng",
        // Chinese simplified
        "ZH_CN_假如",
        "ZH_CN_假设",
        "ZH_CN_假定",
        "ZH_CN_当",
        "ZH_CN_那么",
        "ZH_CN_而且",
        "ZH_CN_并且",
        "ZH_CN_同时",
        "ZH_CN_但是",
        // Chinese traditional
        "ZH_TW_假如",
        "ZH_TW_假設",
        "ZH_TW_假定",
        "ZH_TW_當",
        "ZH_TW_那麼",
        "ZH_TW_而且",
        "ZH_TW_並且",
        "ZH_TW_同時",
        "ZH_TW_但是",
    ]
}
